### PR TITLE
Add params to apiMethod call

### LINKED ISSUE #4: Add additional request params to apiMethod
@boo1ean, what do you think about add second parameter to `apiMethod`.
For example, we can set additional headers to request.

```
apiClient.method({
    param: 'someParam'
}, {
    headers: {
        Authentication: "token GITHUB-TOKEN"
    }
});
```

This can resolve problem with usage github api.

### PR DESCRIPTION
**Pull request by aivus**
Close #4

### CODE REVIEW

**Comment by aivus** [comment]
I'll add some tests soon

**Comment by aivus** [comment]
I added tests and update README.md
@boo1ean, can you review PR?

**Comment by aivus** [comment]
@boo1ean ping

**Comment by boo1ean** [comment]
@aivus Sorry for huge delay :)

**Pull request merged**
